In [2]:
# import pandas as pd
# import numpy as np
# df=pd.read_csv('ecommerce_sales_data.csv')
# df

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("engrmazeem/e-commerce-sales-data")

print("Path to dataset files:", path)

Path to dataset files: /Users/danuzz/.cache/kagglehub/datasets/engrmazeem/e-commerce-sales-data/versions/1

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv(f'{path}/ecommerce_sales_data.csv')
df

,Order ID,Product Name,Category,Price,Quantity,Total Sales,Customer ID,Customer Age,Customer Gender,Purchase Date,Purchase Time
0,261e3740-c0e9-42b1-bf87-881ac950fa3a,audience,Home & Garden,766.85,4,3067.40,81af1248-afff-46ee-a091-81cf33d0d957,39,Male,25/05/2024,6:28:14
1,0b332b34-46dc-4eaf-a808-fec7e97ffbc6,such,Clothing,331.42,4,1325.68,f3f3f4ac-7ad0-4362-9134-383096d16ac8,21,Male,04/05/2024,19:37:36
2,432e0b36-724d-4521-85ae-f66db8af8105,read,Clothing,708.10,10,7081.00,c4fc4269-3c1d-4b6b-ad23-d437c328d63f,27,Female,07/05/2024,17:54:42
3,ca20fb08-5c65-43b8-9577-3fa49913f93b,skill,Electronics,774.09,2,1548.18,578e2d1a-d92a-449d-8eeb-b704110b2975,51,Female,23/05/2024,22:31:43
4,1dce189c-8c60-455f-a6f2-69bb2cb71539,cold,Electronics,397.22,1,397.22,dc6ed196-0874-46bd-bbb9-c5534f619349,45,Female,15/03/2024,3:08:25
...,...,...,...,...,...,...,...,...,...,...,...
99995,67e1224d-86a1-411c-a880-69c3786a15e9,lot,Toys,777.82,2,1555.64,a38aebb9-d3b4-468b-a999-e6d26d62635f,32,Male,01/05/2024,4:49:40
99996,9ad2bf4d-9453-472a-ae50-9d6d2cf8e5e4,animal,Clothing,473.23,1,473.23,4fa8f362-4897-4633-995d-ec5acffbb4d7,48,Female,21/05/2024,9:13:18
99997,43c58940-e1ab-4e8a-8cea-f02811904c06,simply,Electronics,591.40,8,4731.20,190b3b11-217d-43ed-b6d2-aa55be036c85,41,Male,25/03/2024,13:34:07
99998,97b93cc6-93e1-487b-94d3-8b02e6f74038,lose,Clothing,490.93,1,490.93,60e350b2-601a-401c-a8f7-f45e827a6594,56,Female,01/06/2024,3:09:28
99999,192e6ac4-2d97-4055-bec9-d0175f768ec3,nothing,Home & Garden,938.06,8,7504.48,a060dacf-962a-464c-a5c5-a5de55014e3b,46,Male,30/05/2024,20:12:20

In [5]:
df.describe()

               Price       Quantity    Total Sales  Customer Age
count  100000.000000  100000.000000  100000.000000  100000.00000
mean      550.550363       5.493160    3027.926702      44.01757
std       260.558267       2.882013    2274.140853      15.30850
min       100.050000       1.000000     100.050000      18.00000
25%       323.967500       3.000000    1153.515000      31.00000
50%       551.100000       5.000000    2433.885000      44.00000
75%       777.125000       8.000000    4443.337500      57.00000
max       999.990000      10.000000    9999.400000      70.00000

In [6]:
df.info

<bound method DataFrame.info of                                    Order ID Product Name       Category  \
0      261e3740-c0e9-42b1-bf87-881ac950fa3a     audience  Home & Garden
1      0b332b34-46dc-4eaf-a808-fec7e97ffbc6         such       Clothing
2      432e0b36-724d-4521-85ae-f66db8af8105         read       Clothing
3      ca20fb08-5c65-43b8-9577-3fa49913f93b        skill    Electronics
4      1dce189c-8c60-455f-a6f2-69bb2cb71539         cold    Electronics
...                                     ...          ...            ...
99995  67e1224d-86a1-411c-a880-69c3786a15e9          lot           Toys
99996  9ad2bf4d-9453-472a-ae50-9d6d2cf8e5e4       animal       Clothing
99997  43c58940-e1ab-4e8a-8cea-f02811904c06       simply    Electronics
99998  97b93cc6-93e1-487b-94d3-8b02e6f74038         lose       Clothing
99999  192e6ac4-2d97-4055-bec9-d0175f768ec3      nothing  Home & Garden

        Price  Quantity  Total Sales                           Customer ID  \
0      766.85         4      3067.40  81af1248-afff-46ee-a091-81cf33d0d957
1      331.42         4      1325.68  f3f3f4ac-7ad0-4362-9134-383096d16ac8
2      708.10        10      7081.00  c4fc4269-3c1d-4b6b-ad23-d437c328d63f
3      774.09         2      1548.18  578e2d1a-d92a-449d-8eeb-b704110b2975
4      397.22         1       397.22  dc6ed196-0874-46bd-bbb9-c5534f619349
...       ...       ...          ...                                   ...
99995  777.82         2      1555.64  a38aebb9-d3b4-468b-a999-e6d26d62635f
99996  473.23         1       473.23  4fa8f362-4897-4633-995d-ec5acffbb4d7
99997  591.40         8      4731.20  190b3b11-217d-43ed-b6d2-aa55be036c85
99998  490.93         1       490.93  60e350b2-601a-401c-a8f7-f45e827a6594
99999  938.06         8      7504.48  a060dacf-962a-464c-a5c5-a5de55014e3b

       Customer Age Customer Gender Purchase Date Purchase Time
0                39            Male    25/05/2024       6:28:14
1                21            Male    04/05/2024      19:37:36
2                27          Female    07/05/2024      17:54:42
3                51          Female    23/05/2024      22:31:43
4                45          Female    15/03/2024       3:08:25
...             ...             ...           ...           ...
99995            32            Male    01/05/2024       4:49:40
99996            48          Female    21/05/2024       9:13:18
99997            41            Male    25/03/2024      13:34:07
99998            56          Female    01/06/2024       3:09:28
99999            46            Male    30/05/2024      20:12:20

[100000 rows x 11 columns]>

In [7]:
df.isnull()

,Order ID,Product Name,Category,Price,Quantity,Total Sales,Customer ID,Customer Age,Customer Gender,Purchase Date,Purchase Time
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.count()

In [ ]:
df.dtypes

In [ ]:
df['Customer Gender'].value_counts()

In [ ]:
# df.iloc[0]: Select the first row by position

print(df.iloc[0])

In [ ]:
# df.loc[...]: Select specific columns
subset = df.loc[0:5, ['Order ID', 'Category', 'Price', 'Customer Gender']]
display(subset)

In [ ]:
# Sort by Category (A-Z) then Amount (High to Low)
sorted_df = df.sort_values(by=['Category', 'Price'], ascending=[True, False])

In [ ]:
# Sort by Category (A-Z) then Amount (High to Low)
sorted_df = df.sort_values(by=['Category', 'Price'], ascending=[True, False])

display(sorted_df[['Category', 'Price', 'Purchase Date']].head())

In [ ]:
# ## 2. Transformation (Sorting & Filtering)
# **Concepts:** `sort_values`, `query`, boolean masking.

In [ ]:
# Task: Find the Top 5 costliest orders in 'Western Dress' category
# Syntax: df.sort_values(['col1', 'col2'], ascending=[True, False])

In [8]:
sorted_df=df.sort_values(by=['Purchase Date','Total Sales'],ascending=[True,False])
display(sorted_df[['Purchase Date','Total Sales','Product Name']].head())
sorted_df

      Purchase Date  Total Sales Product Name
50887    01/01/2024       9999.4        every
36087    01/01/2024       9736.4          yes
31222    01/01/2024       9671.9       system
47096    01/01/2024       9624.3    professor
6571     01/01/2024       9514.6       behind

,Order ID,Product Name,Category,Price,Quantity,Total Sales,Customer ID,Customer Age,Customer Gender,Purchase Date,Purchase Time
50887,c53426a0-b6ec-4bbb-a59c-9d46eaae5092,every,Home & Garden,999.94,10,9999.40,59fedcf1-59a3-427b-87c1-12d109a689d6,36,Female,01/01/2024,5:43:39
36087,9d7e1a5b-d1ac-4439-a1d3-ddda7a07a8f2,yes,Clothing,973.64,10,9736.40,fd4444d5-4ac9-44e9-8dce-f208f0415c3b,57,Female,01/01/2024,8:03:53
31222,1277c5eb-7361-453a-b5ad-4fbf153f5480,system,Home & Garden,967.19,10,9671.90,0084c222-55d4-4e50-a099-4f63119efa87,40,Male,01/01/2024,17:46:36
47096,4a1363da-1257-4ff2-b508-08cbb7d29ea7,professor,Home & Garden,962.43,10,9624.30,c2eaa0b2-d13e-4ed0-b7ce-989b1968b1de,48,Male,01/01/2024,14:35:05
6571,ad03bed6-7990-4d25-9b27-7d9ba0a2d80e,behind,Toys,951.46,10,9514.60,75aaca99-f056-419a-b20d-f24eaeee4ab2,61,Female,01/01/2024,12:07:35
...,...,...,...,...,...,...,...,...,...,...,...
28030,b4ac6683-37d7-44d9-88d8-1cb466e7a81a,long,Books,166.40,1,166.40,f5b62a29-5f7a-4a07-9904-e52e79534edd,42,Male,31/05/2024,1:59:57
14186,758d404c-b65c-4f79-8c7f-173ddfa327a1,young,Toys,160.35,1,160.35,dfce6ce5-021f-474b-affa-8dc5d1641a22,48,Male,31/05/2024,20:50:34
74813,53dcf0b3-3a2a-41df-b405-f2f558a889cd,agent,Books,157.57,1,157.57,75ddfe01-cfed-420f-9ecc-ff801eee87e7,38,Male,31/05/2024,19:28:11
42141,93018098-c3c9-452d-b138-e73c4a5f7b82,indeed,Home & Garden,135.06,1,135.06,43bacc6e-1caf-475c-9ced-7f71400b9767,21,Male,31/05/2024,13:32:17
12435,62a7ac35-4e2f-4d80-a960-2c45915f744d,spend,Books,101.80,1,101.80,e37ce25c-ac48-4585-925b-2b23457dc23f,35,Female,31/05/2024,8:52:35

In [9]:
df['Category'].value_counts()

Category
Clothing         20144
Home & Garden    20074
Books            20027
Electronics      19899
Toys             19856
Name: count, dtype: int64

Filtering:

In [ ]:
### Filtering

# Method 1: Boolean Masking
mask = (df['Price'] > 990) & (df['Category'] == 'Electronics')
print(f"High Value of Electronics Orders (Mask): {len(df[mask])}")

In [ ]:
mask = (df['Customer Gender'] == 'Female') & (df['Total Sales'] > 900)
print(f"Count (Mask): {len(df[mask])}")

In [ ]:
#method 2: Query syntax

filtering_query = df.query('Price>990 & Category == "Electronics"')
print(f"High Value of Electronics Orders (Query): {len(filtering_query)}")
display(filtering_query[['Order ID', 'Price']].head(3))

In [ ]:
query_df = df.query("`Customer Gender` == 'Female' and `Customer Age` < 20")
print(f"Count (Query): {len(query_df)}")

display(query_df.head(3))

In [ ]:
def classify_age(age):
    if age <30:
        return 'Young'
    elif age <50:
        return 'Middle-aged'
    else:
        return 'Senior'
    #apply to customer age column
df['Age Group'] = df['Customer Age'].apply(classify_age)
df[['Customer Age', 'Age Group']].head(10)

#verify
print(df['Age Group'].value_counts())
display(df[['Customer Age', 'Age Group']].head(10))

In [ ]:
import matplotlib.pyplot as plt
age=df['Age Group'].value_counts()
print(age)
df.plot()

In [ ]:
pip install matplotlib

In [ ]:
pip install matplotlib

In [ ]:
#grouping and aggregating
grouped_df = df.groupby('Category').agg({
    'Total Sales': 'sum',
    'Order ID': 'count'
}).rename(columns={'Order ID': 'Number of Orders'})
display(grouped_df)

In [ ]:
# Group by Category, Sum the Total Sales
cat_performance = df.groupby('Category')['Total Sales'].sum().reset_index()

# Sort for better view
cat_performance = cat_performance.sort_values('Total Sales', ascending=False)

# Format as currency string for readability
pd.options.display.float_format = '${:,.2f}'.format

display(cat_performance)

In [ ]:
aged_df = df.groupby('Age Group').agg({
    'Total Sales': 'sum',
    'Order ID': 'count'
}).rename(columns={'Order ID': 'Number of Orders'})
display(aged_df)

In [ ]:
cat_performance = df.groupby(['Category']).agg({
    'Total Sales': ['sum', 'mean', 'max'],
    'Order ID': 'count'
})
display(cat_performance)

In [ ]:
# ### B. Advanced Aggregation
# **Task:** Analyze `Total Sales` by `Age Group`.
#
# We want: Min, Max, Average, and Count of sales.
age_group_performance = df.groupby('Age Group').agg({
    'Total Sales': ['min', 'max', 'mean'],
    'Order ID': 'count'
})
display(age_group_performance)

In [ ]:
total_sales = df['Total Sales'].sum()
print(f"Total Sales: ${total_sales:,.2f}")

In [ ]:
cust=df.groupby('Customer ID')['Total Sales'].sum().reset_index()
cust=cust.sort_values('Total Sales',ascending=False)
display(cust)