PANDAS SERIES

In [3]:
# ### Pandas – Loading and Cleaning Data
# Today, we'll learn to use **Pandas**, the most essential tool in a Python data scientist's toolkit, to take a raw,
# messy dataset and turn it into a clean, reliable foundation for analysis.
#
#
# 1.  The Building Blocks:** What are Pandas `Series` and `DataFrames`?
# 2.  Getting the Data:** Reading CSV files and first-look inspection.
# 3.  The Cleaning Workflow:**
#     *   Handling Missing Values (`NaN`)
#     *   Finding and Removing Duplicates
#     *   Correcting Data Types and Formatting
# 4.  Exporting Our Clean Data.**
# 5.  Assignment Walkthrough and Q&A.**

In [4]:
# The two core data structures in Pandas.
#
# *   **`Series`**: A one-dimensional labeled array, like a single column in a spreadsheet.
# *   **`DataFrame`**: A two-dimensional labeled data structure with columns of potentially different types, like a full spreadsheet or an SQL table.
#
# Let's quickly create them to see how they work. First, we need to import pandas. The standard convention is to import it as `pd`.

In [5]:
import pandas as pd
a=[1,2,3,4]
s=pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
ice_cream =["Chocolate","Vanilla","Strawberry, Pistachio"]
s=pd.Series(ice_cream)
print(s)

0                Chocolate
1                  Vanilla
2    Strawberry, Pistachio
dtype: object

In [7]:
lottery_numbers = [4, 8, 15, 16, 23, 42]
s = pd.Series(lottery_numbers)
print(s)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [8]:
registrations = [True, False, False, False, True]
pd.Series(registrations)

0     True
1    False
2    False
3    False
4     True
dtype: bool

In [9]:
sushi = {
    "Salmon": "Orange",
    "Tuna": "Red",
    "Eel": "Brown"
}

pd.Series(sushi)

Salmon    Orange
Tuna         Red
Eel        Brown
dtype: object

In [10]:
lottery_dict ={ "anuj":5 ,"panuz":10,"nuz":15}
pd.Series(lottery_dict)

anuj      5
panuz    10
nuz      15
dtype: int64

In [11]:
a = [1, 2, 3, 4]
s = pd.Series(a, index=['a', 'b', 'c', 'd'])
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
a=["anuj","panuz","nuz"]
b =[21,22,23]
s=pd.Series(b,index=a)
print(s)

anuj     21
panuz    22
nuz      23
dtype: int64

In [13]:
# A Series can have a custom index
student_names = pd.Series(
    [85, 92, 78],
    index=['Alice', 'Bob', 'Charlie']
)
print("A Series :")
print(student_names)

A Series :
Alice      85
Bob        92
Charlie    78
dtype: int64

DATA FRAME

In [14]:
# ### Creating a `DataFrame`
#
# A `DataFrame` is the most common object you'll work with. It's a collection of Series. The most common way to create one from scratch is using a dictionary.

In [15]:
data ={
    'StudentID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Score': [85, 92, 78, 88]
}

student_df =pd.DataFrame(data)
print("A DataFrame :")
student_df

A DataFrame :

   StudentID     Name  Score
0        101    Alice     85
1        102      Bob     92
2        103  Charlie     78
3        104    David     88

In [16]:
student_df =pd.DataFrame(data,index=data['StudentID'])
print("A DataFrame :")
student_df

A DataFrame :

     StudentID     Name  Score
101        101    Alice     85
102        102      Bob     92
103        103  Charlie     78
104        104    David     88

PANDAS CSV

In [17]:
messy_data_csv = """OrderID,OrderDate,Product,Price,Quantity,Region
1001,2023-01-05,Laptop,$100,2,North
1002,2023-01-07,Mouse,$25.50,5,South
1003,2023-01-10,Keyboard,,3,North
1004,2023-01-12,Monitor,$300,,"West"
1005,2023-01-15,Webcam,$45.99,1,East
1002,2023-01-07,Mouse,$25.50,5,South
1006,2023-01-18,,$15.00,2,East
1007,2023-01-20,Laptop,$1200.00,1, North
1008,2023-01-22,External HDD,$80,4,USA
"""
with open ("sales_data_messy.csv","w") as file:
    file.write(messy_data_csv)
print("'sales_data_messy.csv' created.")

'sales_data_messy.csv' created.

In [20]:
df = pd.read_csv("sales_data_messy.csv")
print("Loaded DataFrame:")
df

Loaded DataFrame:

   OrderID   OrderDate       Product     Price  Quantity  Region
0     1001  2023-01-05        Laptop      $100       2.0   North
1     1002  2023-01-07         Mouse    $25.50       5.0   South
2     1003  2023-01-10      Keyboard       NaN       3.0   North
3     1004  2023-01-12       Monitor      $300       NaN    West
4     1005  2023-01-15        Webcam    $45.99       1.0    East
5     1002  2023-01-07         Mouse    $25.50       5.0   South
6     1006  2023-01-18           NaN    $15.00       2.0    East
7     1007  2023-01-20        Laptop  $1200.00       1.0   North
8     1008  2023-01-22  External HDD       $80       4.0     USA

In [21]:
dir(df)

['OrderDate',
 'OrderID',
 'Price',
 'Product',
 'Quantity',
 'Region',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [26]:
# ### First-Look Inspection: The "Medical Checkup" for Data
#
# Never start cleaning without a proper checkup. These are your essential first commands.
#
# *   `.head()`: View the first 5 rows.
# *   `.tail()`: View the last 5 rows.
# *   `.shape`: Get the number of rows and columns (rows, columns).
# *   `.info()`: **CRUCIAL!** Get a summary of the DataFrame, including data types and non-null counts.
# *   `.describe()`: Get a statistical summary of the numerical columns.

print("First 5 rows:")
df.head()

First 5 rows:

   OrderID   OrderDate   Product   Price  Quantity Region
0     1001  2023-01-05    Laptop    $100       2.0  North
1     1002  2023-01-07     Mouse  $25.50       5.0  South
2     1003  2023-01-10  Keyboard     NaN       3.0  North
3     1004  2023-01-12   Monitor    $300       NaN   West
4     1005  2023-01-15    Webcam  $45.99       1.0   East

In [27]:
print("Last 5 rows:")
df.tail()

Last 5 rows:

   OrderID   OrderDate       Product     Price  Quantity  Region
4     1005  2023-01-15        Webcam    $45.99       1.0    East
5     1002  2023-01-07         Mouse    $25.50       5.0   South
6     1006  2023-01-18           NaN    $15.00       2.0    East
7     1007  2023-01-20        Laptop  $1200.00       1.0   North
8     1008  2023-01-22  External HDD       $80       4.0     USA

In [28]:
df.shape

(9, 6)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    9 non-null      int64
 1   OrderDate  9 non-null      object
 2   Product    8 non-null      object
 3   Price      8 non-null      object
 4   Quantity   8 non-null      float64
 5   Region     9 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 564.0+ bytes

In [30]:
df.describe()

           OrderID  Quantity
count     9.000000  8.000000
mean   1004.222222  2.875000
std       2.438123  1.642081
min    1001.000000  1.000000
25%    1002.000000  1.750000
50%    1004.000000  2.500000
75%    1006.000000  4.250000
max    1008.000000  5.000000